'use client';
import {useEffect,useState} from 'react';
import {concepts} from '../data/concepts';
const worlds=[['Psychology','How minds judge, learn, remember and relate.',true],['Neuroscience','Brain systems, perception and behavior.',false],['Philosophy','Ideas about meaning, self, freedom and society.',false],['Human Body','Anatomy, physiology and the machinery of being alive.',false],['Middle East','People, institutions and turning points since 1850.',false],['Eastern Europe','Empires, communism, Yugoslavia and transition.',false]];
const sample=(exclude=[])=>[...concepts.filter(c=>!exclude.includes(c.id))].sort(()=>Math.random()-.5).slice(0,5);
export default function Home(){
 const [screen,setScreen]=useState('home'),[cards,setCards]=useState([]),[concept,setConcept]=useState(null),[picked,setPicked]=useState(null),[seen,setSeen]=useState([]),[known,setKnown]=useState([]);
 useEffect(()=>{try{setSeen(JSON.parse(localStorage.getItem('ce-seen')||'[]'));setKnown(JSON.parse(localStorage.getItem('ce-known')||'[]'))}catch{}},[]);
 const save=(s,k=known)=>{setSeen(s);setKnown(k);localStorage.setItem('ce-seen',JSON.stringify(s));localStorage.setItem('ce-known',JSON.stringify(k))};
 const discover=()=>{setCards(sample());setScreen('browse');setConcept(null);setPicked(null)};
 const open=c=>{setConcept(c);setPicked(null);setScreen('play');if(!seen.includes(c.id))save([...seen,c.id])};
 const answer=i=>{setPicked(i);if(i===concept.answer&&!known.includes(concept.id))save(seen,[...known,concept.id])};
 const related=()=>open(concepts.find(x=>concept.related.includes(x.id)&&x.id!==concept.id)||concepts.find(x=>x.id!==concept.id));
 return <main><nav><button className="brand" onClick={()=>setScreen('home')}><span>CE</span> Curiosity Engine</button><div className="navright"><span>{seen.length} discovered</span><button className="ghost" onClick={()=>setScreen('worlds')}>Worlds</button></div></nav>
 {screen==='home'&&<section className="hero"><div className="eyebrow">LEARN SIDEWAYS</div><h1>Find something<br/><i>worth knowing.</i></h1><p className="lead">Five ideas. Pick the one that catches you. Understand it in a few minutes. Then wander somewhere else.</p><button className="primary big" onClick={discover}>Show me 5 ideas <b>→</b></button><p className="sub">No streaks. No homework. Just curiosity.</p><div className="preview"><span>Today you might discover</span><div>{concepts.slice(0,3).map((c,i)=><article key={c.id}><small>0{i+1} · {c.pool}</small><h3>{c.name}</h3><p>{c.hook}</p></article>)}</div></div></section>}
 {screen==='worlds'&&<section className="wrap"><div className="eyebrow">WORLDS</div><h2>What are you curious about?</h2><p className="muted">Each world is a growing collection of ideas worth carrying around.</p><div className="worldgrid">{worlds.map(([n,d,on],i)=><button key={n} className={'world '+(!on?'locked':'')} onClick={()=>on&&discover()}><small>0{i+1}</small><h3>{n}</h3><p>{d}</p><b>{on?'Explore →':'Coming soon'}</b></button>)}</div></section>}
 {screen==='browse'&&<section className="wrap browse"><div className="browsehead"><div><div className="eyebrow">PSYCHOLOGY · DISCOVERY</div><h2>Which one pulls you in?</h2></div><button className="ghost" onClick={()=>setCards(sample(cards.map(x=>x.id)))}>Shuffle ↻</button></div><div className="cardstack">{cards.map((c,i)=><button className="conceptcard" onClick={()=>open(c)} key={c.id}><span className="num">0{i+1}</span><div><small>{c.pool}</small><h3>{c.name}</h3><p>{c.hook}</p></div><b>→</b></button>)}</div><p className="hint">There is no best choice. Follow the question you want answered.</p></section>}
 {screen==='play'&&concept&&<section className="lesson wrap"><button className="back" onClick={()=>setScreen('browse')}>← Back to five</button><div className="eyebrow">{concept.pool.toUpperCase()} · QUICK DISCOVERY</div><h2>{concept.name}</h2><p className="question">{concept.question}</p><div className="answers">{concept.options.map((o,i)=><button disabled={picked!==null} className={picked===null?'':i===concept.answer?'correct':picked===i?'wrong':''} onClick={()=>answer(i)} key={o}><span>{String.fromCharCode(65+i)}</span>{o}</button>)}</div>{picked!==null&&<div className="reveal"><div className="result">{picked===concept.answer?'That’s it.':'Here’s the interesting part.'}</div><h3>What’s going on?</h3><p>{concept.reveal}</p><h3>See it in the wild</h3><div className="examples">{concept.examples.map(([a,b])=><div key={a}><b>{a}</b><p>{b}</p></div>)}</div><div className="why"><small>WHY IT MATTERS</small><p>{concept.why}</p>{concept.caveat&&<p className="caveat"><b>Keep in mind:</b> {concept.caveat}</p>}</div><div className="next"><button className="primary" onClick={discover}>5 new concepts →</button><button className="ghost" onClick={related}>Related concept</button></div></div>}</section>}</main>
}